name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.11.4
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_at_rest

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fhir: ^0.11.4
  # fhir: 
  #   path: ../fhir
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
 
dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.24.7
