name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.11.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fhir: ^0.11.1
  # fhir: 
  #   path: ../fhir
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  json_annotation: ^4.8.1
 
dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.0
  test: ^1.24.3
